version: "3"
services:
  mysql:
    image: mariadb:10.4.12
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: e5sub
      MYSQL_DATABASE: e5sub
    restart: always
    container_name: mysql
  e5bot:
    image: iyear/e5subbot
    volumes:
      - ./e5sub/config.yml:/root/config.yml
      - ./e5sub/log:/root/log
    restart: always
    container_name: fle5
